<script setup lang="ts">
import type { Comment } from '~/types/admin'
definePageMeta({ layout: 'admin', middleware: 'admin-auth' })
const api = useAdminApi(); const toast = useToast(); const pendingOnly = ref(false)
const { data: comments, refresh, status: loadStatus, error } = useLazyAsyncData('admin-comments', () => api.get<Comment[]>('comments/admin/all'))
const visible = computed(() => (comments.value || []).filter(comment => !pendingOnly.value || comment.status === 'pending'))
async function setStatus(comment: Comment, value: string) { await api.patch(`comments/admin/${comment.id}/status`, { status: value }); toast.add({ title: '评论状态已更新', color: 'success' }); await refresh() }
async function remove(comment: Comment) { if (!confirm('删除这条评论？')) return; await api.del(`comments/admin/${comment.id}`); await refresh() }
</script>
<template><div class="space-y-5"><div class="flex items-end justify-between"><div><p class="text-sm text-muted">互动管理</p><h2 class="text-2xl font-semibold">评论</h2></div><USwitch v-model="pendingOnly" label="仅待审核" /></div><UAlert v-if="loadStatus === 'error'" color="error" title="评论加载失败" :description="error?.message" /><div v-else-if="loadStatus === 'pending' || loadStatus === 'idle'" class="space-y-3"><USkeleton v-for="item in 3" :key="item" class="h-28 w-full" /></div><div v-else class="space-y-3"><UCard v-for="comment in visible" :key="comment.id"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div class="flex gap-2"><strong>{{ comment.author || '匿名访客' }}</strong><UBadge>{{ comment.status || 'pending' }}</UBadge></div><p class="mt-2 text-sm text-toned">{{ comment.content }}</p></div><div class="flex gap-1"><UButton size="xs" color="success" variant="soft" @click="setStatus(comment, 'approved')">通过</UButton><UButton size="xs" color="warning" variant="soft" @click="setStatus(comment, 'pending')">待审</UButton><UButton size="xs" color="error" variant="ghost" icon="i-lucide-trash-2" aria-label="删除" @click="remove(comment)" /></div></div></UCard><UEmpty v-if="!visible.length" title="没有符合条件的评论" /></div></div></template>
