export type Article = { id: number; title: string; slug?: string; content?: string; contentMarkdown?: string; category?: string; tags?: string[]; coverImage?: string; aiSummary?: string; createdAt?: string; updatedAt?: string }
export type Comment = { id: number; articleId: number; author?: string; content?: string; status?: string; createdAt?: string }
export type GalleryItem = { id: number; imageUrl: string; tag?: string; isActive?: boolean; sortOrder?: number; imageWidth?: number; imageHeight?: number; createdAt?: string }
export type GalleryHeroSection = 'fade' | 'accordion' | 'coverflow' | 'preview'
export type GalleryHeroItem = { id?: number; imageUrl: string; sourceImageUrl?: string; sortOrder?: number; section?: GalleryHeroSection }
export type GalleryHeroConfiguration = { isConfigured: boolean; sections: Record<GalleryHeroSection, GalleryHeroItem[]> }
export type ImagebedConfig = { domain: string; uploadFolder?: string; configured?: boolean }
export type AuthResponse = { success: boolean; message?: string; token?: string; refreshToken?: string; expiresAt?: string }
export type DiaryEntry = { entryDate: string; contentMarkdown?: string; mood?: string; weather?: string; location?: string; tags?: string[]; isPublic?: boolean; createdAt?: string; updatedAt?: string }
export type DiaryMood = 'happy' | 'excited' | 'calm' | 'busy' | 'tired' | 'cozy' | 'pensive'
export type DiaryWeather = 'sunny' | 'cloudy' | 'overcast' | 'rain' | 'thunder' | 'haze'
