<script setup lang="ts">
import type { GalleryItem } from '~/types/admin'
definePageMeta({ layout: 'admin', middleware: 'admin-auth', keepalive: true })
const api = useAdminApi(); const toast = useToast()
const open = ref(false); const importOpen = ref(false); const editing = ref<GalleryItem | null>(null)
const form = reactive({ imageUrl: '', tag: 'artwork', isActive: true, sortOrder: 0 })
const batch = reactive({ imageUrls: '', tag: 'artwork', isActive: true })
const { data: items, refresh } = await useAsyncData('admin-gallery', () => api.get<GalleryItem[]>('gallery/admin'))
function edit(item?: GalleryItem) { editing.value = item || null; Object.assign(form, item ? { imageUrl: item.imageUrl, tag: item.tag || 'artwork', isActive: item.isActive !== false, sortOrder: item.sortOrder || 0 } : { imageUrl: '', tag: 'artwork', isActive: true, sortOrder: (items.value?.length || 0) + 1 }); open.value = true }
async function save() { if (editing.value) await api.patch(`gallery/${editing.value.id}`, form); else await api.post('gallery', form); open.value = false; toast.add({ title: '画廊已保存', color: 'success' }); await refresh() }
async function importBatch() { const imageUrls = batch.imageUrls.split('\n').map(value => value.trim()).filter(Boolean); if (!imageUrls.length) return; await api.post('gallery/batch/import', { imageUrls, tag: batch.tag, isActive: batch.isActive }); importOpen.value = false; batch.imageUrls = ''; toast.add({ title: `已导入 ${imageUrls.length} 张图片`, color: 'success' }); await refresh() }
async function saveOrder() { const updates = (items.value || []).map((item, index) => ({ id: item.id, sortOrder: index + 1 })); await api.patch('gallery/batch/sort-order', updates); toast.add({ title: '排序已保存', color: 'success' }); await refresh() }
function move(index: number, direction: -1 | 1) { const list = items.value || []; const next = index + direction; if (next < 0 || next >= list.length) return; const current = list[index]; const target = list[next]; if (!current || !target) return; list[index] = target; list[next] = current }
async function toggle(item: GalleryItem) { await api.patch(`gallery/${item.id}/toggle-active`); await refresh() }
async function remove(item: GalleryItem) { if (!confirm('删除该画廊项？')) return; await api.del(`gallery/${item.id}`); await refresh() }
</script>
<template><div class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-muted">视觉内容</p><h2 class="text-2xl font-semibold">画廊</h2></div><div class="flex flex-wrap gap-2"><UButton color="neutral" variant="soft" @click="api.post('gallery/refresh-dimensions').then(() => refresh())">刷新尺寸</UButton><UButton color="neutral" variant="soft" @click="saveOrder">保存排序</UButton><UButton color="neutral" variant="soft" @click="importOpen = true">批量导入</UButton><UButton icon="i-lucide-plus" @click="edit()">添加图片</UButton></div></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><UCard v-for="(item, index) in items" :key="item.id" :ui="{ body: 'p-0' }"><img :src="item.imageUrl" :alt="item.tag || 'gallery image'" class="aspect-square w-full object-cover" /><div class="space-y-3 p-3"><div class="flex justify-between gap-2"><strong class="truncate">{{ item.tag || 'artwork' }}</strong><UBadge :color="item.isActive ? 'success' : 'neutral'">{{ item.isActive ? '显示' : '隐藏' }}</UBadge></div><div class="flex justify-end gap-1"><UButton size="xs" color="neutral" variant="ghost" icon="i-lucide-arrow-up" :disabled="index === 0" aria-label="上移" @click="move(index, -1)" /><UButton size="xs" color="neutral" variant="ghost" icon="i-lucide-arrow-down" :disabled="index === (items?.length || 0) - 1" aria-label="下移" @click="move(index, 1)" /><UButton size="xs" color="neutral" variant="ghost" icon="i-lucide-pencil" aria-label="编辑" @click="edit(item)" /><UButton size="xs" color="neutral" variant="ghost" icon="i-lucide-eye" aria-label="切换显示" @click="toggle(item)" /><UButton size="xs" color="error" variant="ghost" icon="i-lucide-trash-2" aria-label="删除" @click="remove(item)" /></div></div></UCard></div><UModal v-model:open="open" title="画廊项"><template #body><UForm :state="form" class="space-y-4" @submit="save"><UFormField label="图片地址"><UInput v-model="form.imageUrl" class="w-full" /></UFormField><UFormField label="标签"><UInput v-model="form.tag" class="w-full" /></UFormField><UFormField label="排序"><UInput v-model.number="form.sortOrder" type="number" class="w-full" /></UFormField><USwitch v-model="form.isActive" label="公开显示" /><UButton type="submit" block>保存</UButton></UForm></template></UModal><UModal v-model:open="importOpen" title="批量导入"><template #body><UForm :state="batch" class="space-y-4" @submit="importBatch"><UFormField label="每行一个图片地址"><UTextarea v-model="batch.imageUrls" :rows="8" class="w-full" /></UFormField><UFormField label="标签"><UInput v-model="batch.tag" class="w-full" /></UFormField><USwitch v-model="batch.isActive" label="公开显示" /><UButton type="submit" block>导入</UButton></UForm></template></UModal></div></template>
